"""empty message

Revision ID: 666c020b6492
Revises: 02165707b3d0
Create Date: 2018-11-19 23:33:14.393000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666c020b6492'
down_revision = '02165707b3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'author_id')
    # ### end Alembic commands ###
